name: Publish

on:
  push:
    branches: # Snapshots
      - 3.0.x
    tags: ["**"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v4
    with:
      java: 11
    secrets: inherit
